module.exports.errorMessage = {
    EMAIL_ALREADY_EXIST: "Email đã tồn tại",
    EMAIL_NOT_FOUND: "Email không tồn tại",
    PASSWORD_NOT_MATCH: "Mật khẩu không đúng",
    UNAUTHORIZED: "Không có quyền truy cập",
    TOKEN_EXPIRED: "Token đã hết hạn",
    USER_NOT_FOUND: "Người dùng không tồn tại",
    ADD_CATEGORY_FAIL: "Thêm danh mục thất bại",
    UPLOAD_IMAGE_FAIL: "Tải ảnh lên thất bại",
    PRODUCT_NOT_FOUND: "Sản phẩm không tồn tại",
    PRODUCT_ALREADY_IN_CART: "Sản phẩm đã có trong giỏ hàng",
    COUPONS_NOT_FOUND: "Mã giảm giá không tồn tại",
    COUPONS_EXPIRED: "Mã giảm giá đã hết hạn",
    PRODUCT_ALREADY_IN_WISHLIST: "Sản phẩm đã có trong danh sách yêu thích",
    ADD_REVIEW_FAIL: "Bạn chưa mua sản phẩm này",
    ALREADY_REVIEWED: "Bạn đã đánh giá sản phẩm này",
    ACTIVE_ACCOUNT_PAYMENT_FAIL: "Kích hoạt tài khoản thanh toán thất bại",
    SEND_REQUEST_WITHDRAWAL_FAIL: "Số dư tài khoản không đủ để rút tiền",
    OLD_PASSWORD_NOT_MATCH: "Mật khẩu cũ không đúng",
    PASSWORD_AND_CONFIRM_PASSWORD_NOT_MATCH: "Mật khẩu mới và xác nhận mật khẩu không khớp",
};

module.exports.successMessage = {
    LOGIN_SUCCESS: "Đăng nhập thành công",
    REGISTER_SUCCESS: "Đăng ký thành công",
    LOGOUT_SUCCESS: "Đăng xuất thành công",
    VERIFY_EMAIL: "Vui lòng kiểm tra email và xác thực tài khoản",
    ADD_CATEGORY_SUCCESS: "Thêm danh mục thành công",
    ADD_PRODUCT_SUCCESS: "Thêm sản phẩm thành công",
    UPDATE_PRODUCT_SUCCESS: "Cập nhật sản phẩm thành công",
    DELETE_PRODUCT_SUCCESS: "Xóa sản phẩm thành công",
    UPLOAD_IMAGE_SUCCESS: "Tải ảnh lên thành công",
    ADD_PROFILE_SUCCESS: "Thêm thông tin cá nhân thành công",
    UPDATE_SELLER_STATUS_SUCCESS: "Cập nhật trạng thái seller thành công",
    ADD_TO_CART_SUCCESS: "Thêm vào giỏ hàng thành công",
    DELETE_PRODUCT_CART_SUCCESS: "Xóa sản phẩm khỏi giỏ hàng thành công",
    INCREASE_QUANTITY_SUCCESS: "Đã tăng số lượng",
    DECREASE_QUANTITY_SUCCESS: "Đã giảm số lượng",
    ADD_COUPONS_SUCCESS: "Thêm mã giảm giá thành công",
    UPDATE_COUPONS_SUCCESS: "Cập nhật mã giảm giá thành công",
    DELETE_COUPONS_SUCCESS: "Xóa mã giảm giá thành công",
    APPLY_COUPONS_SUCCESS: "Áp dụng mã giảm giá thành công",
    ORDER_SUCCESS: "Đặt hàng thành công",
    ADD_TO_WISHLIST_SUCCESS: "Thêm vào danh sách yêu thích thành công",
    DELETE_WISHLIST_SUCCESS: "Xóa khỏi danh sách yêu thích thành công",
    ADD_REVIEW_SUCCESS: "Thêm đánh giá thành công",
    SEND_MESSAGE_SUCCESS: "Gửi tin nhắn thành công",
    CHANGE_STATUS_ORDER_SUCCESS: "Thay đổi trạng thái đơn hàng thành công",
    ACTIVE_ACCOUNT_PAYMENT_SUCCESS: "Kích hoạt tài khoản thanh toán thành công",
    UPDATE_PAYMENT_SUCCESS: "Cập nhật trạng thái thanh toán thành công",
    SEND_REQUEST_WITHDRAWAL_SUCCESS: "Yêu cầu rút tiền thành công",
    CONFIRM_WITHDRAWAL_REQUEST_SUCCESS: "Xác nhận yêu cầu rút tiền thành công",
    CHANGE_PASSWORD_SUCCESS: "Đổi mật khẩu thành công",
    REPLY_REVIEW_SUCCESS: "Trả lời đánh giá thành công",
};
