const path = {
    seller_login: "/seller-login",
    seller_register: "/seller-register",
    admin_login: "/admin-login",
    admin_dashboard: "/admin/dashboard",
    admin_dashboard_orders: "/admin/dashboard/orders",
    admin_dashboard_categories: "/admin/dashboard/categories",
    admin_dashboard_sellers: "/admin/dashboard/sellers",
    admin_dashboard_coupons: "/admin/dashboard/coupons",
    admin_dashboard_payments: "/admin/dashboard/payments-request",
    admin_dashboard_sellers_request: "/admin/dashboard/sellers-request",
    admin_dashboard_sellers_details: "/admin/dashboard/sellers/details/:sellerId",
    admin_dashboard_orders_details: "/admin/dashboard/orders/details/:orderId",
    admin_dashboard_deactive: "/admin/dashboard/deactive-sellers",
    admin_dashboard_chat: "/admin/dashboard/chat",
    admin_dashboard_chat_seller: "/admin/dashboard/chat/:sellerId",
    seller_dashboard: "/seller/dashboard",
    seller_dashboard_products: "/seller/dashboard/products",
    seller_dashboard_edit_product: "/seller/dashboard/edit-product/:productId",
    seller_dashboard_discount: "/seller/dashboard/discount",
    seller_dashboard_orders: "/seller/dashboard/orders",
    seller_dashboard_orders_details: "/seller/dashboard/orders/details/:orderId",
    seller_dashboard_payment: "/seller/dashboard/payments-request",
    seller_dashboard_chat_admin: "/seller/dashboard/chat-admin",
    seller_dashboard_chat_customers: "/seller/dashboard/chat-customers",
    seller_dashboard_chat_customer_id: "/seller/dashboard/chat-customers/:customerId",
    seller_dashboard_profile: "/seller/dashboard/profile",
    seller_dashboard_blog: "/seller/dashboard/blog",
    seller_dashboard_reply_review: "/seller/dashboard/reply-review",
    seller_account_deactive: "/seller/account-deactive",
    seller_account_pending: "/seller/account-pending",
    unauthorized: "/unauthorized",
    payment_success: "/success?",
    home: "/",
};

export default path;
